### ISSUE TITLE
Sobolev_filter symmetrical grid trick

### ISSUE THREAD

**Issue by bazpasha** [adler-j/bwgan#1]
We are doing project on your paper. We've read your code for sobolev_filter and faced problems with understanding the trick you use for \xi grid. As far as we understood, the straight-forward way to do scaling is to make a meshgrid using range(sx) / sx and range(sy) / sy. But we found out that you do it in a symmetric-way, i.e. minimum(x, sx - x) / (sx // 2). We wonder why you do it like that? Are there any reasons like numerical stability, etc.? It is also interesting why one needs to limit |\xi| <= 5, does constant "c" in your code have any correlation with this constraint? And if yes, why it is not in the Sobolev-norm equation?

**Comment by adler-j** [comment]
> We are doing project on your paper.

Phenomenal to hear! I'll try to answer the best I can.

> As far as we understood, the straight-forward way to do scaling is to make a meshgrid using range(sx) / sx and range(sy) / sy. But we found out that you do it in a symmetric-way, i.e. minimum(x, sx - x) / (sx // 2). We wonder why you do it like that?

What we want is that X and Y correspond to (normalized) frequencies. Hence X=0, Y=0 should correspond to the zero (constant) frequency. Where this zero frequency is placed in the result of the FFT  depends on the shift employed by the Fourier transform. The TF fourier transform has the zero frequency in the middle of the image (this is different from e.g. numpy, which is "centered" at the corners and one has to use fftshift to move it).

> Are there any reasons like numerical stability, etc.?

No, it is simply convenience, we could also have e.g. employed  fftshift and moved it to the "normal" place (but beware of aliasing!)

> It is also interesting why one needs to limit |\xi| <= 5, does constant "c" in your code have any correlation with this constraint?

The constant c in our code is indeed that number.

> And if yes, why it is not in the Sobolev-norm equation?

It is actually in the Sobolev norm equation, it's just that you don't immediately see it. Perhaps we were not perfectly clear about this in the article.

To elaborate, the Sobolev norm is not scale invariant in a nice way. This means that if we rescale the domain then the value of the sobolev norms change in non-linear manners. The smaller the domain, the more important the gradients become. This is in contrast to standard Lp-norms that change linearly with scaling, so scaling doesn't matter to much for them.

Hence, the scale of the domain actually matters when we define Sobolev norms. In this work we empirically picked the scaling such that the maximum frequency is about 5.

**Comment by bazpasha** [comment]
Thank you a lot for your answer! Now it is clear, we did not take into account a TF unconventional implementation of FFT :)

**Comment by adler-j** [comment]
Cheers! If everything is fine I'll close this.
